# Generated by Django 5.1 on 2024-09-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('team', models.CharField(max_length=3)),
                ('position', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('points', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('penalty_minutes', models.IntegerField()),
                ('even_goals', models.IntegerField()),
                ('power_play_goals', models.IntegerField()),
                ('short_hand_goals', models.IntegerField()),
                ('game_winning_goals', models.IntegerField()),
                ('even_time_on_ice', models.FloatField()),
                ('power_play_time_on_ice', models.FloatField()),
                ('short_hand_time_on_ice', models.FloatField()),
                ('shots_on_goal', models.IntegerField()),
                ('shooting_percentage', models.FloatField()),
                ('total_shots_attempted', models.IntegerField()),
                ('time_on_ice', models.FloatField()),
                ('average_time_on_ice', models.FloatField()),
                ('faceoffs_won', models.IntegerField()),
                ('faceoffs_lost', models.IntegerField()),
                ('faceoff_percentage', models.FloatField()),
                ('blocks', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('takeaways', models.IntegerField()),
                ('giveaways', models.IntegerField()),
            ],
        ),
    ]
