# Generated by Django 5.1 on 2024-09-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_playerstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='rank',
        ),
    ]
