# Generated by Django 5.1 on 2024-09-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_playerstat_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
