# Generated by Django 5.1 on 2024-09-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_playerstat_awards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstat',
            old_name='blocks',
            new_name='blocked_shots',
        ),
        migrations.RenameField(
            model_name='playerstat',
            old_name='faceoffs_lost',
            new_name='short_hand',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='even_time_on_ice',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='faceoffs_won',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='power_play_time_on_ice',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='short_hand_time_on_ice',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='even_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='faceoff_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='faceoff_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='power_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='awards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='faceoff_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='player',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='team',
            field=models.CharField(max_length=50),
        ),
    ]
