# Generated by Django 5.1 on 2024-09-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_blocks_playerstat_blocked_shots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='faceoff_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
