# Generated by Django 5.1 on 2024-09-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_playerstat_faceoff_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='shooting_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
